---
- name: Stop Nexus Service
  systemd:
    name: nexus.service
    state: stopped

- name: Change to the directory
  shell: "cd /apps/ && ls -alt"
  args:
    executable: /bin/bash

- name: Zip current nexus application folder
  shell: "bakup_version=nexus_{{ current_version }} && zip -r ${bakup_version}.zip nexus/"
  args:
    chdir: /apps
    executable: /bin/bash

- name: Make directory for Nexus latest versions
  file:
    path: /apps/{{ jira_card }}
    state: directory

- name: Download Latest nexus version 
  get_url:
    url: "https://download.sonatype.com/nexus/3/latest-unix.tar.gz" 
    dest: /apps/{{ jira_card }}/nexus.tar.gz

- name: Extract New Nexus Archive
  unarchive:
    src: /apps/{{ jira_card }}/nexus.tar.gz
    dest: /apps/{{ jira_card }}
    remote_src: yes

- name: Remove Nexus current version
  file:
    path: /apps/nexus
    state: absent

- name: Move Nexus latest version to Apps repository
  command: mv /apps/{{ jira_card }}/nexus-3* /apps/nexus

- name: Set Nexus Ownership
  file:
    path: /apps/nexus
    owner: nexus
    group: nexus
    recurse: yes

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Restart Nexus Service
  systemd:
    name: nexus
    state: restarted

- name: Remove working directory
  file:
    path: /apps/{{ jira_card }}
    state: absent