- name: apt update
  apt:
    update_cache: yes

- name: Install Nginx@Latest
  apt:
    name: nginx
    state: latest
  notify:
    - restart nginx

- name: Run test services
  include_tasks: test_services.yml
  when: nginx_restart_triggered

