- name: apt update
  apt:
    update_cache: yes

- name: Install Nginx@Latest
  apt:
    name: nginx
    state: latest
  notify:
    - restart nginx

- name: Test Nginx
  uri:
    url: http://localhost
    status_code: 200
  register: result
  until: result.status == 200
  retries: 10
  delay: 2

