---
- name: Change Directory to Nexus Application/
  shell:
    cmd: "cd /apps/ && ls -alt"
    executable: /bin/bash

- name: Zip Nexus current version for backup
  shell:
    cmd: "bakup_version=nexus_{{ current_version }} && zip -r ${bakup_version}.zip nexus/"
    executable: /bin/bash

- name: Create New Nexus App Directory
  shell:
    cmd: "mkdir -p {{ nexus_install_dir }}" # What is ##JIRA_CARD##?

- name: Download Latest nexus version 
  get_url:
    url: "https://download.sonatype.com/nexus/3/latest-unix.tar.gz"
    dest: "{{ nexus_install_dir }}/nexus.tar.gz"
  become: yes

- name: Extract New Nexus Archive
  become: yes
  unarchive:
    src: "{{ nexus_install_dir }}/nexus.tar.gz"
    dest: "{{ nexus_install_dir }}/nexus.tar.gz"
    remote_src: yes

- name: Remove Nexus current version
  file:
    path: "{{ nexus_apps_dir }}"
    state: absent

- name: Move Nexus latest version to Apps repository
  ansible.builtin.mv:
    src: "{{ nexus_install_dir }}/nexus-3*" # if its stll >= 3.0 version
    dest: "{{ nexus_apps_dir }}"

- name: Set Nexus Ownership
  become: yes
  file:
    path: "{{ nexus_apps_dir }}"
    owner: appservice
    group: appservice
    recurse: yes

- name: Start Nexus Service
  become: yes
  systemd:
    name: nexus
    state: restarted

- name: Remove working directory
  become: yes
  file:
    path: "{{ nexus_install_dir }}"
    state: absent
