---
- name: Install Sonatype Nexus
  hosts: aella-xplatform-mpoc-poc-ansible-dev-ec2
  become: yes

  vars:
    nexus_home: "/apps/nexus"
    nexus_data: "/apps/sonatype-work"
    nexus_user: "nexus"
    nexus_service: "nexus.service"

  tasks:
    # - name: Install Java
    #   apt:
    #     name: openjdk-11-jdk
    #     state: present

    - name: Create Nexus user
      user:
        name: "{{ nexus_user }}"
        system: yes
        shell: /bin/false

    - name: Download Nexus
      get_url:
        url: "https://download.sonatype.com/nexus/3/latest-unix.tar.gz"
        dest: "/tmp/nexus-latest-unix.tar.gz"

    - name: Create /apps directory
      file:
        path: /apps
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Extract Nexus
      unarchive:
        src: "/tmp/nexus-latest-unix.tar.gz"
        dest: "{{ nexus_home }}"
        remote_src: yes

    - name: Set permissions
      file:
        path: "{{ item }}"
        owner: "{{ nexus_user }}"
        group: "{{ nexus_user }}"
        mode: '0755'
        recurse: yes
      with_items:
        - "{{ nexus_home }}"
        - "{{ nexus_data }}"

    - name: Ensure nexus binary is executable
      file:
        path: "{{ nexus_home }}/nexus-3*/bin/nexus"
        mode: '0755'

    - name: Configure Nexus to run as a service
      copy:
        dest: /etc/systemd/system/{{ nexus_service }}
        content: |
          [Unit]
          Description=nexus service
          After=network.target

          [Service]
          Type=forking
          LimitNOFILE=65536
          ExecStart={{ nexus_home }}/bin/nexus start
          ExecStop={{ nexus_home }}/bin/nexus stop
          User={{ nexus_user }}
          Restart=on-abort

          [Install]
          WantedBy=multi-user.target
    
    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start Nexus service
      systemd:
        name: "{{ nexus_service }}"
        enabled: yes
        state: started

    - name: Configure Nexus Data Directory
      lineinfile:
        path: "{{ nexus_home }}/bin/nexus.vmoptions"
        line: "-Dkaraf.data={{ nexus_data }}"
        create: yes
