---
- name: Install Sonatype Nexus
  hosts: aella-xplatform-mpoc-poc-ansible-dev-ec2
  become: yes

  vars:
    nexus_home: "/apps/nexus"
    nexus_user: "nexus"
    nexus_service: "nexus.service"

  tasks:
    - name: Create Nexus user
      user:
        name: "{{ nexus_user }}"
        system: yes
        shell: /bin/false

    - name: Create directory for Nexus installation
      file:
        path: /apps/nexus
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Download Latest Nexus version 
      get_url:
        url: "https://download.sonatype.com/nexus/3/latest-unix.tar.gz" 
        dest: /apps/nexus/nexus.tar.gz

    - name: Extract Nexus Archive
      unarchive:
        src: /apps/nexus/nexus.tar.gz
        dest: /apps/nexus
        remote_src: yes

    - name: Find extracted Nexus directory
      shell: "ls -d /apps/nexus/nexus-*/"
      register: nexus_extracted_dir
      ignore_errors: yes

    - name: Debug extracted directory
      debug:
        var: nexus_extracted_dir.stdout

    - name: Move extracted Nexus files
      command: mv {{ item }}* /apps/nexus/
      with_items: "{{ nexus_extracted_dir.stdout_lines }}"
      when: nexus_extracted_dir.stdout_lines is defined and nexus_extracted_dir.stdout_lines|length > 0

    - name: Remove extracted directory
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ nexus_extracted_dir.stdout_lines }}"
      when: nexus_extracted_dir.stdout_lines is defined and nexus_extracted_dir.stdout_lines|length > 0

    - name: Set Nexus Ownership
      file:
        path: /apps/nexus
        owner: "{{ nexus_user }}"
        group: "{{ nexus_user }}"
        recurse: yes

    - name: Create Nexus systemd service file
      copy:
        dest: /etc/systemd/system/{{ nexus_service }}
        content: |
          [Unit]
          Description=nexus service
          After=network.target

          [Service]
          Type=forking
          ExecStart=/apps/nexus/bin/nexus start
          ExecStop=/apps/nexus/bin/nexus stop
          User={{ nexus_user }}
          Restart=on-abort

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start Nexus Service
      systemd:
        name: nexus
        state: started
        enabled: yes
