- name: Ensure Java is installed (Debian-based)
  apt:
    name: openjdk-17-jdk
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure Java is installed (RedHat-based)
  yum:
    name: java-17-openjdk
    state: present
  when: ansible_os_family == "RedHat"

- name: Create nexus user
  user:
    name: nexus
    home: /opt/nexus
    shell: /bin/bash
    create_home: yes

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: nexus
    group: nexus
  with_items:
    - /opt/nexus
    - /opt/sonatype-work

- name: Download Nexus
  get_url:
    url: "https://download.sonatype.com/nexus/3/latest-unix.tar.gz"
    dest: /tmp/nexus.tar.gz

- name: Extract Nexus
  unarchive:
    src: /tmp/nexus.tar.gz
    dest: /opt/nexus
    remote_src: yes
    extra_opts:
      - --strip-components=1
  notify: Restart Nexus

- name: Change ownership of nexus directory
  file:
    path: /opt/nexus
    state: directory
    owner: nexus
    group: nexus
    recurse: yes

- name: Create nexus.service systemd file
  template:
    src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service

- name: Enable and start Nexus service
  ansible.builtin.systemd:
    name: nexus
    enabled: yes
    state: started

