---
- name: Create Nexus user
  ansible.builtin.user:
    name: nexus
    home: /opt/nexus
    shell: /bin/bash
    state: present

- name: Download Nexus
  get_url:
    url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
    dest: /tmp/nexus.tar.gz

- name: Extract Nexus
  ansible.builtin.unarchive:
    src: /tmp/nexus.tar.gz
    dest: /opt/
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: Change ownership of Nexus directory
  ansible.builtin.file:
    path: /opt/nexus
    owner: nexus
    group: nexus
    recurse: yes

- name: Create nexus.service systemd file
  template:
    src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service

- name: Enable and start Nexus service
  ansible.builtin.systemd:
    name: nexus
    state: started
    enabled: yes


- name: Set JAVA_HOME environment variable
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: 'JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64'
    create: yes
  become: yes
