- name: Create directory for Nexus installation
  file:
    path: /apps/nexus
    state: directory
    # owner: nexus
    # group: appservice

- name: Download Latest Nexus version 
  get_url:
    url: "https://download.sonatype.com/nexus/3/latest-unix.tar.gz" 
    dest: /apps/nexus/nexus.tar.gz

- name: Extract Nexus Archive
  unarchive:
    src: /apps/nexus/nexus.tar.gz
    dest: /apps/nexus
    remote_src: yes

- name: Move extracted Nexus files
  command: mv /apps/nexus/nexus-3*/* /apps/nexus/

# - name: Set Nexus Ownership
#   file:
#     path: /apps/nexus
#     owner: nexus
#     group: appservice
#     recurse: yes

- name: Create Nexus systemd service file
  copy:
    dest: /etc/systemd/system/nexus.service
    content: |
      [Unit]
      Description=nexus service
      After=network.target

      [Service]
      Type=forking
      ExecStart=/apps/nexus/bin/nexus start
      ExecStop=/apps/nexus/bin/nexus stop
      User=appservice
      Restart=on-abort

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Start Nexus Service
  systemd:
    name: nexus
    state: started
    enabled: yes