- name: Create nexus user
  user:
    name: nexus
    home: /apps/nexus
    shell: /bin/bash
    create_home: yes

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: nexus
    group: nexus
  with_items:
    - /apps/nexus
    - /apps/sonatype-work

- name: Download Nexus
  get_url:
    url: "https://download.sonatype.com/nexus/3/latest-unix.tar.gz"
    dest: /apps/tmp/nexus.tar.gz

- name: Extract Nexus
  become: yes
  unarchive:
    src: /apps/tmp/nexus.tar.gz
    dest: /apps/nexus
    remote_src: yes
    extra_opts:
      - --strip-components=1
  notify: Restart Nexus

- name: Change ownership of nexus directory
  file:
    path: /apps/nexus
    state: directory
    owner: nexus
    group: nexus
    recurse: yes

- name: Create nexus.service systemd file
  template:
    src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service

- name: Start Nexus Service
  become: yes
  systemd:
    name: nexus
    state: restarted

- name: Remove working directory
  become: yes
  file:
    path: /apps/{{ jira_card }}
    state: absent

