- hosts: webservers
  become: yes
  become_user: root
  become_method: sudo
  become_password: 1234
  tasks:

    - name: update
      apt: update_cache=yes

    - name: Install Nginx
      apt: name=nginx state=latest

      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=reloaded