---
- name: Install Nexus Repository Manager 3
  hosts: slave-3
  become: yes

  vars:
    nexus_version: "3.69.0-02"
    java_version: "17"
    nexus_download_url: "https://download.sonatype.com/nexus/3/nexus-{{ nexus_version }}-java{{ java_version }}-unix.tar.gz"
    nexus_install_dir: "/opt/nexus"
    nexus_data_dir: "/opt/sonatype-work"
    nexus_user: "nexus"

  tasks:
    - name: ติดตั้ง dependencies
      apt:
        name: 
          - wget
          - openjdk-{{ java_version }}-jdk
        state: present
        update_cache: yes

    - name: สร้างผู้ใช้ nexus
      user:
        name: "{{ nexus_user }}"
        shell: /bin/bash

    - name: ดาวน์โหลด Nexus Repository Manager
      get_url:
        url: "{{ nexus_download_url }}"
        dest: "/tmp/nexus-{{ nexus_version }}-unix.tar.gz"

    - name: สร้างไดเรกทอรีสำหรับติดตั้ง Nexus
      file:
        path: "{{ nexus_install_dir }}"
        state: directory
        owner: "{{ nexus_user }}"
        group: "{{ nexus_user }}"

    - name: แตกไฟล์ Nexus Repository Manager
      unarchive:
        src: "/tmp/nexus-{{ nexus_version }}-unix.tar.gz"
        dest: "{{ nexus_install_dir }}"
        remote_src: yes
        creates: "{{ nexus_install_dir }}/nexus-{{ nexus_version }}"

    - name: สร้าง symbolic link ไปที่ nexus
      file:
        src: "{{ nexus_install_dir }}/nexus-{{ nexus_version }}"
        dest: "{{ nexus_install_dir }}/nexus"
        state: link
        force: yes

    - name: สร้างไดเรกทอรีสำหรับข้อมูลของ Nexus
      file:
        path: "{{ nexus_data_dir }}"
        state: directory
        owner: "{{ nexus_user }}"
        group: "{{ nexus_user }}"

    - name: ตั้งค่าการอนุญาตบนไดเรกทอรีของ Nexus
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ nexus_user }}"
        group: "{{ nexus_user }}"
        recurse: yes
      with_items:
        - "{{ nexus_install_dir }}/nexus"
        - "{{ nexus_data_dir }}"

    - name: ตั้งค่าให้ Nexus ทำงานในฐานะผู้ใช้ nexus
      lineinfile:
        path: "{{ nexus_install_dir }}/nexus/bin/nexus.vmoptions"
        line: "-Djava.io.tmpdir={{ nexus_data_dir }}"
        create: yes

    - name: ตั้งค่าให้ Nexus ใช้ Java 17
      lineinfile:
        path: "{{ nexus_install_dir }}/nexus/bin/nexus"
        regexp: '^#INSTALL4J_JAVA_HOME_OVERRIDE='
        line: 'INSTALL4J_JAVA_HOME_OVERRIDE=/usr/lib/jvm/java-{{ java_version }}-openjdk-amd64'
        insertafter: '^#INSTALL4J_JAVA_HOME_OVERRIDE='

    - name: สร้างไฟล์บริการ Nexus สำหรับ SysVinit
      copy:
        dest: /etc/init.d/nexus
        content: |
          #!/bin/bash
          # Nexus service script
          # chkconfig: 345 99 10
          # description: Nexus service

          case "$1" in
          start)
            echo "Starting Nexus..."
            su - {{ nexus_user }} -c "{{ nexus_install_dir }}/nexus/bin/nexus start"
            ;;
          stop)
            echo "Stopping Nexus..."
            su - {{ nexus_user }} -c "{{ nexus_install_dir }}/nexus/bin/nexus stop"
            ;;
          restart)
            echo "Restarting Nexus..."
            su - {{ nexus_user }} -c "{{ nexus_install_dir }}/nexus/bin/nexus stop"
            su - {{ nexus_user }} -c "{{ nexus_install_dir }}/nexus/bin/nexus start"
            ;;
          status)
            su - {{ nexus_user }} -c "{{ nexus_install_dir }}/nexus/bin/nexus status"
            ;;
          *)
            echo "Usage: $0 {start|stop|restart|status}"
            exit 1
          esac

          exit 0
      mode: '0755'

    - name: เปิดใช้งานบริการ Nexus ด้วย SysVinit
      command: update-rc.d nexus defaults

    - name: เริ่มบริการ Nexus ด้วย SysVinit
      service:
        name: nexus
        state: started